# This is a basic workflow to help you get started with Actions

name: Liquibase_Docker_GitHub-Hosted

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
     branches: 
        "main"
     paths:
     - 'dbscript/deploy/**'
    #e  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run 'Liquibase status' in a Docker Container
        uses: docker://liquibase/liquibase:latest 
        with: 
          args: --url=${{secret.SF_URL}} --changeLogFile=/dbscript/masterChangelog.xml --username=${{secret.SF_USERNAME}} --password=${{secret.SF_PASSWORD}} --driver=${{secret.SF_DRIVER}} --schema=${{secret.SF_SCHEMA}}
      
      - name: Run 'Liquibase update' in a Docker Container
        uses: docker://liquibase/liquibase:latest 
        with: 
          args: --url=${{secret.SF_URL}} --changeLogFile=/dbscript/masterChangelog.xml --username=${{secret.SF_USERNAME}} --password=${{secret.SF_PASSWORD}} --driver=${{secret.SF_DRIVER}} --schema=${{secret.SF_SCHEMA}}
